apiVersion: v1
kind: Pod
metdata:
  name: my-multicontainer-app

spec:
  containers:
    - name: my-multicontainer-app
      image: nginx
      ports:
        - containerPorts: 8080
    - name: log-agent
      image: log-agent

## This is the concept of "Multi Container" pod so we can break Monolithic application to Microservices.
## The containers inside the pods can access to each other and can share same storage.



