apiVersion: v1
kind: Pod
metadata:
  name: mysecret-app-color

spec:
  container:
    - name: mysecret-app-color
      image: mysecret-app-color
      ports:
        - containerPort: 8080
      ebvFrom:
        - secretRef:
            name: app-secret