apiVersion: v1
kind: Secret
metadata:
  name: app-secret

data:
  DB_Host: bXlzcWw=
  DB_USer: cm9vdA==
  DB_Password: QXZpQDEyMzQ1

## The aboe DB details is encoded with command echo -n "value" | base64
## To decode the value use command echo -n "value" | base64 --decode
## However encoding data with base64 is not safe and anybody can crack it.
## To secure in a more robust way, use Helm Secrets, HashiCorp Vault.